travis:
  secure:
    BINSTAR_TOKEN: MgyVbWGaWgY4hqF3ojhdRUVUfviyPKzlevRYVq/YkqozPw+Ks8XL62vOQLM//sOZnf2nZSAwTr9mEbn8P2A40+oMglkjinvs8Nrx8AZTt6vVfQwaTn7KY7updS8YGKRL0GshzrY0XjJDFojQHBTHf4dsoqrmBzN4PFrbacY1mwi52H2gNRX3eFVT3B50h+KHHsvEluBrV1jJQ6adR5fNaCKNkNfSbGcjNtLirFFd020LAYDfQeNQh1W75PKuC7tHl5RQeXSvVasBOXeStfHTj8JiKZgOeOHb3PsSSQbZ0jT07rViLa3ozpSuItt1gcbQVkuNcDRJnJgx2E/yZRAdO2e5nyh2LsQ6Xgf74XTcfjYq1/nhma9OCkwVppKIswjgHovKLWKdRrMsHTZbc15L2NWcdq4WLL+h+TvyBB4R5IVD5/fGZiBDIGwMTNfXH3MnOYQWgh2m5wZQcHlAj/k+tSX8tf5GAYABQgGkxVLG6rxIMZdeLp96ADoSfe35t/7widMRPz25zBcabMnE+zJv6svb/S+mjOaS6p/1GoeOvct7c/6feZLZ31RXvPJlJd6r1r5KmT8ITfdK3vGNlAXKXzBGuimsiEeMRMJhSXTNZr+Gmp4DY7dBVtlM+bNu1SJMIiccQhPCEcw6/7lt1flbutD2rUh9A2ZwPfq57ulcY9g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
